# Generated by Django 3.0.2 on 2020-02-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='cash_code',
            field=models.CharField(default='DPC', max_length=12),
        ),
    ]
