# Generated by Django 2.2 on 2020-02-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='payed_on',
        ),
    ]
