# Generated by Django 3.0.2 on 2020-02-01 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_cashtransaction_cash_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
