# Generated by Django 3.0.2 on 2020-02-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_cashtransaction_cash_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='cash_code',
            field=models.CharField(default='KGC', max_length=12),
        ),
    ]
