# Generated by Django 3.0.2 on 2020-02-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200203_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='actr_no',
            field=models.CharField(default='DPP', max_length=7, verbose_name='Payment No'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='cash_code',
            field=models.CharField(default='DPC', max_length=12),
        ),
    ]
