# Generated by Django 3.0.2 on 2020-02-03 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20200203_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='cash_code',
            field=models.CharField(default='KGC', max_length=12),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
