# Generated by Django 3.0.2 on 2020-02-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletadvance',
            name='payment_no',
        ),
    ]
