# Generated by Django 2.2 on 2020-02-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletadvance',
            name='p_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
