# Generated by Django 2.2 on 2020-02-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_walletadvance_p_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletadvance',
            name='payed_on',
        ),
    ]
