# Generated by Django 2.2 on 2020-02-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_remove_walletadvance_payed_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletadvance',
            old_name='p_2',
            new_name='payed_on',
        ),
    ]
