# Generated by Django 3.0.2 on 2020-02-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_walletadvance_payment_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletadvance',
            name='payment_no',
        ),
    ]
