# Generated by Django 2.2 on 2020-02-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_auto_20200206_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletadvance',
            name='payed_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payed On'),
        ),
    ]
