# Generated by Django 3.0.2 on 2020-02-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_remove_walletadvance_payment_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletadvance',
            name='payment_no',
            field=models.CharField(default='DPP', max_length=12),
        ),
    ]
