# Generated by Django 3.0.2 on 2020-02-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0005_walletadvance_payment_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletadvance',
            name='payment_no',
            field=models.CharField(default='KGP', max_length=12),
        ),
    ]
