# Generated by Django 3.0.2 on 2020-02-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_code',
        ),
    ]
