# Generated by Django 3.0.2 on 2020-02-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_code',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
    ]
