# Generated by Django 3.0.2 on 2020-02-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0002_remove_bankaccount_account_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_code',
            field=models.CharField(default='-', max_length=7),
        ),
    ]
