# Generated by Django 3.0.2 on 2020-02-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0003_bankaccount_account_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_code',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
